# Generated by Django 5.2.7 on 2025-11-01 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('university', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('University', models.CharField(max_length=100, null=True)),
                ('Index_number', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarkingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the marking scheme', max_length=255)),
                ('pass_score', models.PositiveIntegerField(default=40, help_text='Minimum score required to pass')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marking_scheme', to='api.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(blank=True, help_text='The text of the question', null=True)),
                ('answer_text', models.TextField(help_text='The text of the answer')),
                ('marks', models.PositiveIntegerField(help_text='Marks allocated for this answer')),
                ('grading_type', models.CharField(choices=[('one-word', 'One Word'), ('short-phrase', 'Short Phrase'), ('list', 'List'), ('numerical', 'Numerical')], default='one-word', max_length=20)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('order_sensitive', models.BooleanField(default=False)),
                ('range_sensitive', models.BooleanField(default=False)),
                ('partial_matching', models.BooleanField(default=False, help_text='For list type answers, allow partial credit for partially correct lists')),
                ('semantic_threshold', models.FloatField(default=0.7, help_text='Threshold for semantic matching (0-1) for short-phrase answers')),
                ('range', models.JSONField(blank=True, default=dict, help_text="Range for numerical answers, e.g., {'min': 0, 'max': 100, 'tolerance_percent': 5}", null=True)),
                ('marking_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.markingscheme')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.lecturer')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.module'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assignments/%Y/%m/%d/')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_hash', models.CharField(max_length=64, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='GradingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('student_answer', models.TextField()),
                ('correct_answer', models.TextField()),
                ('marks_awarded', models.IntegerField(default=0)),
                ('allocated_marks', models.IntegerField()),
                ('grading_type', models.CharField(max_length=20)),
                ('is_correct', models.BooleanField(default=False)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_results', to='api.submission')),
            ],
            options={
                'unique_together': {('submission', 'question_id')},
            },
        ),
    ]
